services:
  jenkins:
    build: .
    container_name: jenkins-devops
    ports:
      - "8080:8080"
      - "50000:50000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  laravel-agent:
    build: ./laravel-agent
    container_name: jenkins-laravel-agent
    env_file:
      - .env.docker
    ports:
      - "2222:22"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always

volumes:
  jenkins_home:
